apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mauritel-api
  labels:
    app: mauritel-api
spec:
  selector:
    matchLabels:
      app: mauritel-api
  replicas: 3
  template:
    metadata:
      labels:
        app: mauritel-api
    spec:
      containers:
      - name: mauritel-api
        image: acodescr001.azurecr.io/elhacendia/acodes-mauritel-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: nmauritel-api-port
