apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mauritel
  labels:
    app: mauritel
spec:
  selector:
    matchLabels:
      app: mauritel
  replicas: 1
  template:
    metadata:
      labels:
        app: mauritel
    spec:
      containers:
      - name: mauritel-api
        image: acodescr001.azurecr.io/elhacendia/acodes-mauritel-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: mauritel-port
