apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mauritel
  labels:
    app: mauritel
spec:
  selector:
    matchLabels:
      app: mauritel
  replicas: 1
  template:
    metadata:
      labels:
        app: mauritel
    spec:
      containers:
      - name: mauritel-api
        image: acodescr001.azurecr.io/elhacendia/acodes-mauritel-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: mauritel-port
      - name: mauritel-ui
        image: acodescr001.azurecr.io/diaabdoul/paybillui
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 4200
          name: ui-port
      imagePullSecrets:
      - name: mauritelsdr

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        imagePullPolicy: "Always"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: operateur
      imagePullSecrets:
      - name: mauritelsdr
        ports:
        - containerPort: 3306
