apiVersion: v1
kind: Service
metadata:
  name: mauritel-ui-svc
  labels:
    app: mauritel
spec:
  ports:
  - port: 80
    targetPort: 4200
  selector:
    app: mauritel
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mauritel-api-svc
  labels:
    app: mauritel
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mauritel
  type: LoadBalancer


